name: docker image build

on:
  workflow_dispatch:

env:
  IMAGE_NAME: hello-html-app


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Build docker image
        run: |
          docker build -t $IMAGE_NAME

      - name: show containers
        run: |
          docker images      
  