name: My-first-workflow

on:
  workflow_dispatch:
    


jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - run: echo "hello sriram"
        
      - name: Meet the runner
        run: |
          hostname
          whoami
          pwd
          ls -la
