name: matrix combination demo

on:
  workflow_dispatch:

jobs:
  demo:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        node-version:
          - 18
          - 20
    runs-on: ${{matrix.os}}

    steps:
      - name: print matrix values
        run: |
          echo "os.${{matrix.os}}"
          echo "Node version: ${{matrix.nodeversion}}"        
              
  
      
