name: parallel-job

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
      - steps:
          run: echo "build finished"
  test:
    runs-on: ubuntu-latest
      - steps:
          run: echo "test finished"
  deploy:
    runs-on: ubuntu-latest
      - steps:
          run: echo "deploy finished"

          