name: html-change

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'

jobs:
  html-check:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4

      - run: cat index.html

